version: '3'

services:
  app:
    container_name: app
    build: 
      context: .docker
    image: go-grpc
    ports:
      - 50051:50051
    expose:
      - 50051
    volumes:
      - ./app:/app/src/
