FROM golang:1.18-alpine

WORKDIR /app/src/

RUN apk update && apk add protobuf && \
    go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28 && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

CMD ["tail","-f","/dev/null"]